/**
 * shake_host.cpp
 *
 * SHAKE Host-Side Implementation — NPU Kernel Launch
 *
 * Uses RegisterAscendBinary to load the SHAKE iteration kernel binary
 * embedded via .inc file (auto-generated by xxd -i on device_aiv.o).
 */
#include "shake_host.h"

// CANN Runtime API declarations
extern "C" {
uint32_t RegisterAscendBinary(const char *fileBuf, size_t fileSize, uint32_t type, void **handle);
uint32_t LaunchAscendKernel(void *handle, const uint64_t key, const uint32_t blockDim,
                            void **args, uint32_t size, const void *stream);
int UnregisterAscendBinary(void *hdl);
uint32_t AllocAscendMemDevice(void **devMem, uint64_t size);
uint32_t FreeAscendMemDevice(void *devMem);
}

// ============================================================
// Embedded kernel binary (auto-generated by xxd -i device_aiv.o)
// xxd -i generates:
//   unsigned char _mnt_..._device_aiv_o[] = { ... };
//   unsigned int _mnt_..._device_aiv_o_len = N;
// We define shorter aliases for readability.
//
// The xxx_o array is the ELF binary itself (ELF magic is at offset 0).
// RegisterAscendBinary accepts this format directly.
// ============================================================
#include "shake_iteration_device_aiv_bin.inc"

// ============================================================
// ShakeHost: Constructor/Destructor
// ============================================================
ShakeHost::ShakeHost() : initialized_(false), acl_initialized_(false),
    n_atoms_(0), n_constraints_(0), max_constraints_allocated_(0),
    max_iterations_(100), tolerance_(1e-10f), dt_sq_(1e-6f),
    device_owns_coords_(false), device_id_(0), context_(nullptr),
    stream_(nullptr), coords_device_(nullptr), constraints_device_(nullptr),
    target_lengths_device_(nullptr), inv_masses_device_(nullptr),
    max_error_device_(nullptr), iterations_(0), max_error_host_(0.0f),
    converged_(false) {}
ShakeHost::~ShakeHost() { Finalize(); }
// ============================================================
// Short alias pointing to xxd's generated symbols
#define SHAKE_BIN _mnt_ssbr_full_process_build_operators_constraints_shake_iteration_kernel_merge_obj_dir_device_aiv_o
#define SHAKE_BIN_LEN _mnt_ssbr_full_process_build_operators_constraints_shake_iteration_kernel_merge_obj_dir_device_aiv_o_len

// ============================================================
// Accessor implementations
// ============================================================
bool ShakeHost::WasConverged() const { return converged_; }
int32_t ShakeHost::GetIterations() const { return iterations_; }
double ShakeHost::GetMaxError() const { return static_cast<double>(max_error_host_); }
float* ShakeHost::GetCoordinatesDevicePtr() { return coords_device_; }

static void* g_shake_iteration_handle = nullptr;
static bool g_shake_iteration_loaded = false;

// ============================================================
// Kernel registration (global — register once)
// ============================================================
static int32_t ShakeHost_InitKernel() {
    if (g_shake_iteration_loaded) return 0;
    uint32_t ret = RegisterAscendBinary(
        (const char*)SHAKE_BIN,
        SHAKE_BIN_LEN,
        1,  // type 1 = AIV
        &g_shake_iteration_handle
    );
    if (ret != 0) {
        fprintf(stderr, "[ShakeHost] RegisterAscendBinary failed: %u\n", ret);
        return -1;
    }
    g_shake_iteration_loaded = true;
    fprintf(stdout, "[ShakeHost] Kernel registered (%u bytes)\n", SHAKE_BIN_LEN);
    return 0;
}

// ============================================================
// Kernel unregistration (global cleanup)
// ============================================================
static void ShakeHost_FiniKernel() {
    if (g_shake_iteration_loaded) {
        UnregisterAscendBinary(g_shake_iteration_handle);
        g_shake_iteration_loaded = false;
        g_shake_iteration_handle = nullptr;
    }
}

// ============================================================
// Helper: aclrtMalloc wrapper for typed pointers
// ============================================================
static int32_t MallocDevice(void** ptr, size_t size) {
    return aclrtMalloc(ptr, size, ACL_MEM_MALLOC_HUGE_FIRST);
}

// ============================================================
// ShakeHost: Initialize with shared ACL context
// ============================================================
int32_t ShakeHost::Initialize(
    int32_t n_atoms,
    const float* inv_masses,
    aclrtContext shared_context,
    aclrtStream shared_stream,
    int32_t device_id,
    float tolerance,
    int32_t max_iterations
) {
    int32_t ret = ShakeHost_InitKernel();
    if (ret != 0) return ret;

    n_atoms_ = n_atoms;
    max_iterations_ = max_iterations;
    tolerance_ = tolerance;
    device_id_ = device_id;
    context_ = shared_context;
    stream_ = shared_stream;
    acl_initialized_ = true;

    ret = AllocateDeviceMemory();
    if (ret != 0) return ret;

    if (inv_masses) {
        aclrtMemcpy(inv_masses_device_, n_atoms_ * sizeof(float),
                    inv_masses, n_atoms_ * sizeof(float),
                    ACL_MEMCPY_HOST_TO_DEVICE);
    } else {
        std::vector<float> ones(n_atoms_, 1.0f);
        aclrtMemcpy(inv_masses_device_, n_atoms_ * sizeof(float),
                    ones.data(), n_atoms_ * sizeof(float),
                    ACL_MEMCPY_HOST_TO_DEVICE);
    }

    float zero = 0.0f;
    aclrtMemcpy(max_error_device_, sizeof(float),
                &zero, sizeof(float),
                ACL_MEMCPY_HOST_TO_DEVICE);

    initialized_ = true;
    fprintf(stdout, "[ShakeHost] Initialized: N=%d, max_iter=%d, tol=%.2e\n",
            n_atoms_, max_iterations_, tolerance_);
    return 0;
}

// ============================================================
// Set constraints
// ============================================================
int32_t ShakeHost::SetConstraints(
    int32_t n_constraints,
    const int32_t* constraints,
    const float* target_lengths,
    float dt
) {
    if (n_constraints <= 0) return -1;

    if (constraints_device_ && max_constraints_allocated_ < n_constraints) {
        aclrtFree(constraints_device_);
        aclrtFree(target_lengths_device_);
        constraints_device_ = nullptr;
        target_lengths_device_ = nullptr;
        max_constraints_allocated_ = 0;
    }

    if (!constraints_device_) {
        if (MallocDevice((void**)&constraints_device_,
                         n_constraints * 2 * sizeof(int32_t)) != ACL_SUCCESS)
            return -1;
        if (MallocDevice((void**)&target_lengths_device_,
                         n_constraints * sizeof(float)) != ACL_SUCCESS)
            return -1;
        max_constraints_allocated_ = n_constraints;
    }

    n_constraints_ = n_constraints;
    dt_sq_ = dt * dt;

    aclrtMemcpy(constraints_device_, n_constraints_ * 2 * sizeof(int32_t),
                constraints, n_constraints_ * 2 * sizeof(int32_t),
                ACL_MEMCPY_HOST_TO_DEVICE);
    aclrtMemcpy(target_lengths_device_, n_constraints_ * sizeof(float),
                target_lengths, n_constraints_ * sizeof(float),
                ACL_MEMCPY_HOST_TO_DEVICE);

    return 0;
}

// ============================================================
// Apply SHAKE (host coordinates)
// ============================================================
int32_t ShakeHost::Apply(float* coords_host) {
    if (!initialized_ || n_constraints_ <= 0) return -1;

    aclrtMemcpy(coords_device_, n_atoms_ * 3 * sizeof(float),
                coords_host, n_atoms_ * 3 * sizeof(float),
                ACL_MEMCPY_HOST_TO_DEVICE);

    int32_t result = ApplyDeviceInternal();

    aclrtMemcpy(coords_host, n_atoms_ * 3 * sizeof(float),
                coords_device_, n_atoms_ * 3 * sizeof(float),
                ACL_MEMCPY_DEVICE_TO_HOST);

    return result;
}

// ============================================================
// Apply SHAKE (device coordinates, no host sync)
// ============================================================
int32_t ShakeHost::ApplyDevice(float* coords_device) {
    if (!initialized_ || n_constraints_ <= 0) return -1;
    coords_device_ = coords_device;
    return ApplyDeviceInternal();
}

// ============================================================
// Internal: convergence loop
// ============================================================
int32_t ShakeHost::ApplyDeviceInternal() {
    iterations_ = 0;
    max_error_host_ = 0.0f;
    converged_ = false;

    for (int32_t iter = 0; iter < max_iterations_; iter++) {
        // Reset max_error to 0 on device
        float zero = 0.0f;
        aclrtMemcpy(max_error_device_, sizeof(float),
                    &zero, sizeof(float),
                    ACL_MEMCPY_HOST_TO_DEVICE);

        if (LaunchIteration() != 0) return -1;

        // Read max_error back
        aclrtMemcpy(&max_error_host_, sizeof(float),
                    max_error_device_, sizeof(float),
                    ACL_MEMCPY_DEVICE_TO_HOST);

        iterations_ = iter + 1;

        if (max_error_host_ < tolerance_) {
            converged_ = true;
            return iter + 1;
        }
    }

    fprintf(stderr, "[ShakeHost] WARNING: Did not converge in %d iters. max_err=%.2e\n",
            max_iterations_, max_error_host_);
    return -iterations_;
}

// ============================================================
// Launch one kernel iteration
// ============================================================
int32_t ShakeHost::LaunchIteration() {
    if (!g_shake_iteration_loaded || !g_shake_iteration_handle) return -1;

    ShakeIterationArgs args;
    args.coords_gm = coords_device_;
    args.constraints_gm = constraints_device_;
    args.target_lengths_gm = target_lengths_device_;
    args.inv_masses_gm = inv_masses_device_;
    args.max_error_gm = max_error_device_;
    args.n_atoms = n_atoms_;
    args.n_constraints = n_constraints_;
    args.dt_sq = dt_sq_;
    args.tolerance = tolerance_;
    // Allocate overflow device memory using AllocAscendMemDevice
    // (same as what autogen host_stub uses — aclrtMalloc may allocate
    //  different memory types that don't work with LaunchAscendKernel)
    void* overflow_dev = nullptr;
    uint32_t aret = AllocAscendMemDevice(&overflow_dev, 8);
    if (aret == 0 && overflow_dev) {
        uint64_t zero = 0;
        aclrtMemcpy(overflow_dev, 8, &zero, 8, ACL_MEMCPY_HOST_TO_DEVICE);
    }
    // Wrapper struct: args + __ascendc_overflow (required for by-value kernel args)
    // NOTE: The args struct is passed by value to the kernel.
    // LaunchAscendKernel needs the raw struct bytes followed by overflow pointer.
    struct {
        ShakeIterationArgs args;
        void* __ascendc_overflow;
    } wrapper;

    memcpy(&wrapper.args, &args, sizeof(ShakeIterationArgs));
    wrapper.__ascendc_overflow = overflow_dev;

    uint32_t ret = LaunchAscendKernel(
        g_shake_iteration_handle, 0, 1,
        (void**)&wrapper, sizeof(wrapper), stream_
    );

    if (overflow_dev) FreeAscendMemDevice(overflow_dev);
    if (ret != 0) {
        fprintf(stderr, "[ShakeHost] LaunchAscendKernel failed: %u\n", ret);
        return -1;
    }
    // Sync
    int32_t sync_ret = aclrtSynchronizeStream(stream_);
    if (sync_ret != ACL_SUCCESS) {
        fprintf(stderr, "[ShakeHost] Stream sync failed: %d (iter %d)\n", sync_ret, iterations_);
        return -1;
    }

    return 0;
}

// ============================================================
// Allocate device memory
// ============================================================
int32_t ShakeHost::AllocateDeviceMemory() {
    aclError ret;
    // CWE-190 fix: cast n_atoms_ to size_t before multiplying so the byte count
    // is computed in 64-bit arithmetic. n_atoms_*3*sizeof(float) overflows int32_t
    // when n_atoms_ > ~715M, which would pass a (truncated) small size to
    // MallocDevice and later overflow the buffer on the device.
    if (n_atoms_ <= 0) {
        fprintf(stderr, "[ShakeHost] AllocateDeviceMemory: invalid n_atoms_=%d\n", n_atoms_);
        return -1;
    }
    // Coordinates + max_error scalar (extra float at end for scalar write-back)
    ret = MallocDevice((void**)&coords_device_,
                       (static_cast<size_t>(n_atoms_) * 3 + 1) * sizeof(float));
    if (ret != ACL_SUCCESS) return ret;
    device_owns_coords_ = true;

    // Place max_error at coords buffer end to avoid cache coherence issues
    // with separate aclrtMalloc allocations on Ascend 910B3.
    max_error_device_ = coords_device_ + static_cast<size_t>(n_atoms_) * 3;

    ret = MallocDevice((void**)&inv_masses_device_, static_cast<size_t>(n_atoms_) * sizeof(float));
    if (ret != ACL_SUCCESS) return ret;

    constraints_device_ = nullptr;
    target_lengths_device_ = nullptr;
    return 0;
}

// ============================================================
// Device memory check — verify writes by reading back
// ============================================================

// ============================================================
// Finalize
// ============================================================
void ShakeHost::Finalize() {
    if (coords_device_ && device_owns_coords_) {
        aclrtFree(coords_device_);
        coords_device_ = nullptr;
        device_owns_coords_ = false;
    }
    if (inv_masses_device_) {
        aclrtFree(inv_masses_device_);
        inv_masses_device_ = nullptr;
    }
    // NOTE: max_error_device_ is an offset pointer into coords_device_ buffer
    // (coords_device_ + n_atoms * 3). It is NOT independently allocated,
    // so we do NOT aclrtFree it here — coords_device_'s free handles it.
    max_error_device_ = nullptr;
    if (constraints_device_) {
        aclrtFree(constraints_device_);
        constraints_device_ = nullptr;
    }
    if (target_lengths_device_) {
        aclrtFree(target_lengths_device_);
        target_lengths_device_ = nullptr;
    }

    ShakeHost_FiniKernel();
    initialized_ = false;
    n_constraints_ = 0;
    max_constraints_allocated_ = 0;
}
